### ISSUE TITLE
Unable to install through `easy_install`

### ISSUE THREAD

**Issue by firegurafiku** [HamsterHuey/easyplot#9]
Hi. I've tried installing the package with `easy_install-3.4` (for some reason I prefer `easy_install` over `pip`), but it has reported me the following error:

```text
$ sudo easy_install-3.4 easyplot
Searching for easyplot
Reading https://pypi.python.org/simple/easyplot/
Best match: EasyPlot 1.0.0
Downloading https://pypi.python.org/packages/source/E/EasyPlot/EasyPlot-1.0.0.zip#md5=31c7bac33a45d02ddc97c8c632f14510
Processing EasyPlot-1.0.0.zip
Writing /tmp/easy_install-kcwzc18c/EasyPlot-1.0.0/setup.cfg
Running EasyPlot-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kcwzc18c/EasyPlot-1.0.0/egg-dist-tmp-3k6fu_ge
error: SandboxViolation: mkdir('/root/.config/matplotlib', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```

Is there something wrong with your `./setup.py` script?

**Comment by HamsterHuey** [comment]
Pavel, I will need to look into this more carefully. Do you have matplotlib
installed locally? If not, that could very well be the issue.

**Comment by firegurafiku** [comment]
No, I'm pretty sure I've installed matplotlib. Moreover, when I tried to make a clean `virtual-env` installation, I ran into trobles once again:
```text
$ virtualenv-3.4 ~/test-venv-3.4
$ ~/test-venv-3.4/bin/easy_install matplotlib
(Lots of output)
$ ~/test-venv-3.4/bin/easy_install easyplot
Searching for easyplot
Reading https://pypi.python.org/simple/easyplot/
Best match: EasyPlot 1.0.0
Downloading https://pypi.python.org/packages/source/E/EasyPlot/EasyPlot-1.0.0.zip#md5=31c7bac33a45d02ddc97c8c632f14510
Processing EasyPlot-1.0.0.zip
Writing /tmp/easy_install-9QtKuA/EasyPlot-1.0.0/setup.cfg
Running EasyPlot-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-9QtKuA/EasyPlot-1.0.0/egg-dist-tmp-Zx5zkw
Traceback (most recent call last):
  File "test-venv-3.4/bin/easy_install", line 11, in <module>
    sys.exit(main())
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2245, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
    run_setup(setup_script, args)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 126, in __exit__
    self._saved = UnpickleableException.dump(type, exc)
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
  File "/home/firegurafiku/test-venv-3.4/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
    return cls.dump(cls, cls(repr(exc)))
MemoryError
```
I don't even know what to think about all of this.

**Comment by HamsterHuey** [comment]
Pavel, thanks for the feedback. I'll have to give this a shot on my machine
to see if I can reproduce the issue. I'm not seeing a clear indication of
what might be causing it from the logs you posted.

If you're still interested in trying out EasyPlot, I'd recommend simply
downloading the EasyPlot.py file and having that somewhere accessible to
your Python install. This is a pretty light weight and simple library and
is contained in one file, so it should be very easy to use even without
going the route of pip/easy install. I used this as a learning experience
to figure out how to put something up on PyPi and have it installable via
pip and easy install. Clearly the latter did not pan out though I'm pretty
sure it worked well for me locally when I first wrote this library.
